package com.wzh.pam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public NewOrder() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public NewOrder(java.lang.String name) {
		this.name = name;
	}

}