---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: containergroup-service-account
  namespace: aap-namespace
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole-containergroup-service-account
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrolebinding-containergroup-service-account
subjects:
- kind: ServiceAccount
  name: containergroup-service-account
  namespace: aap-namespace
roleRef:
  kind: ClusterRole
  name: clusterrole-containergroup-service-account
  apiGroup: rbac.authorization.k8s.io
