FROM flume:wzh

COPY core-site.xml /opt/flume-config/
COPY hdfs-site.xml /opt/flume-config/
COPY schema/* /opt/schema/
COPY flume.conf /opt/flume-config/
COPY morphline.conf /opt/flume-config/
COPY flume-env.sh /opt/flume-config/