---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-dhcp-ds-amd64
  namespace: openshift-sdn
  labels:
    tier: node
    app: dhcp
spec:
  template:
    metadata:
      labels:
        tier: node
        app: dhcp
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: dhcp
      containers:
      - name: kube-dhcp
        # Based on: https://github.com/s1061123/cni-dhcp-daemon/blob/master/Dockerfile
        # image: dougbtv/dhcp:latest
        image: aws-registry.redhat.ren/dougbtv/dhcp
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true