version: '3.7'
services:
  haproxy:
    image: haproxy:2.4
    container_name: external-l4-haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8080:8080"
      - "8404:8404"
    restart: always
