apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sriovnetworks.sriovnetwork.openshift.io
spec:
  group: sriovnetwork.openshift.io
  names:
    kind: SriovNetwork
    listKind: SriovNetworkList
    plural: sriovnetworks
    singular: sriovnetwork
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification describing how a NetworkAttachmentDefinition
            custom resource shall be defined for SR-IOV CNI plugin.
          properties:
            ipam:
              description: IPAM configuration to be used for this network.
              type: string
            networkNamespace:
              description: Namespace of the NetworkAttachmentDefinition custom resource
              type: string
            resourceName:
              description: SRIOV Network device plugin endpoint resource name
              type: string
            spoofChk:
              description: VF spoof check
              type: boolean
            trust:
              description: VF trust mode
              type: boolean
            vlan:
              description: VLAN ID to assign for the VF. Defaults to 0.
              format: int64
              maximum: 4096
              minimum: 0
              type: integer
          required:
          - resourceName
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
