apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: eap-operator.v1.0.0
  namespace: placeholder
  annotations:
    capabilities: Basic Install
    categories: "Application Runtime"
    repository: https://github.com/wildfly/wildfly-operator
    description: Operator that creates and manages Java applications running on JBoss EAP.
    containerImage: registry.redhat.io/jboss-eap-7/eap73-rhel8-operator:1.0
    support: WildFlyServer
    certified: "false"
    createdAt: "2019-06-12T08:00:00Z"
spec:
  displayName: JBoss EAP
  description: |
    ### Optimized for cloud and containers
    JBoss EAP 7 is built to provide simplified deployment and full Java™ EE performance for applications in any environment. Whether on-premise or in virtual, private, public, and hybrid clouds, JBoss EAP features a modular architecture that starts services only as they are required. The extreme low memory footprint and fast startup times mean that JBoss EAP is ideal for environments where efficient resource utilization is a priority, such as Red Hat OpenShift.

    ### Lightweight, flexible architecture
    JBoss EAP 7 is built for high performance and maximum flexibility in modern application environments. Its extremely modular architecture and services-driven set of components reduces scale-out times and provides flexibility for applications deployed in different environments. Well-suited for microservices and traditional applications, JBoss EAP offers the flexibility to build the applications your business requires—from traditional to new web-scale, microservices applications.

    ### More productive developers
    JBoss EAP allows developers to be more productive and responsive to line-of-business demands. Support for Java EE and a wide range of Java EE web-based frameworks, such as Spring, Spring Web Flow, Spring WS, Spring Security, Arquillian, AngularJS, jQuery, jQuery Mobile, and Google Web Toolkit (GWT) comes standard. Use JBoss EAP with common DevOps tools to maximize productivity, decrease quality issues, and get new apps out to market faster.

    ### Flexible management, configuration, and administration
    JBoss EAP 7 maximizes administrative productivity by making it easy to maintain and update your deployments. JBoss EAP 7 features an updated management console user interface with intuitive navigation and support for large-scale domain configurations. The updated command-line interface provides a quick, unified view into configurations and subsystems, while offering the ability to manage servers offline. This can be used with popular configuration management tools, such as Ansible Tower by Red Hat or Puppet—making editing XML configuration files unnecessary.

    ### Flexible, future-friendly subscription model
    A subscription to JBoss EAP provides you both technical and business flexibility. Eliminate upfront, binding licensing decisions that lock you into specific deployment environments, hardware machines, infrastructure, or levels of enterprise support. With a Red Hat subscription, you’re free to build your application and then decide where and how you’ll deploy.

  keywords: ['eap', 'java', 'open source', 'application runtime']
  version: 1.0.0
  maturity: alpha
  minKubeVersion: 1.11.0
  provider:
    name: Red Hat
  labels:
    operated-by: eap-operator
  selector:
    matchLabels:
      operated-by: eap-operator
  links:
    - name: EAP Homepage
      url: https://www.redhat.com/en/technologies/jboss-middleware/application-platform
    - name: Documentation
      url: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/
    - name: Blog
      url: https://developers.redhat.com/blog/
    - name: Quickstart
      url: https://github.com/jboss-developer/jboss-eap-quickstarts
    - name: Red Hat Customer Portal
      url: https://access.redhat.com/support
  maintainers:
    - email: customerservice@redhat.com
      name: Red Hat, Inc.
  icon:
    - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
      mediatype: image/svg+xml
  customresourcedefinitions:
    owned:
      - name: wildflyservers.wildfly.org
        version: v1alpha1
        kind: WildFlyServer
        displayName: WildFlyServer
        description: An application running on EAP application runtime.
        resources:
          - kind: Service
            version: v1
          - kind: Pod
            version: v1
          - kind: StatefulSet
            version: v1beta2
        specDescriptors:
          - description: Desired number of replicas for the application
            displayName: Replicas
            path: replicas
          - description: Name of the application image to be deployed.
            displayName: Application Image
            path: image
          - description: spec to specify how standalone configuration can be read from a ConfigMap.
            displayName: Standalone ConfigMap
            path: standaloneConfigMap
          - description: Storage spec to specify how storage should be used.
            displayName: Storage
            path: storage
          - description: Represent the state of the Pod, it's used especially during scale down the expected values are represented by the PodState constants  Read-only.
            displayName: State
            path: state
          - description: Represents the number of pods which are in scaledown process what particular pod is scaling down can be verified by PodStatus  Read-only.
            displayName: ScalingdownPods
            path: scalingdownPods
  install:
    spec:
      deployments:
      - name: eap-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: eap-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: eap-operator
            spec:
              containers:
              - command:
                - wildfly-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: eap-operator
                image: registry.redhat.io/jboss-eap-7/eap73-rhel8-operator:1.0
                imagePullPolicy: Always
                name: eap-operator
                resources: {}
              serviceAccountName: eap-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - pods/exec
          - pods/log
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - "*"
        - apiGroups:
          - wildfly.org
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: eap-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces