

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/wzh-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: APP_WEB_URL
            - name: AZURE_BLOB_ACCOUNT_KEY
              value: difyai
            - name: AZURE_BLOB_ACCOUNT_NAME
              value: difyai
            - name: AZURE_BLOB_ACCOUNT_URL
              value: https://<your_account_name>.blob.core.windows.net
            - name: AZURE_BLOB_CONTAINER_NAME
              value: difyai-container
            - name: CELERY_BROKER_URL
              value: redis://:difyai123456@redis:6379/1
            - name: CODE_EXECUTION_API_KEY
              value: dify-sandbox
            - name: CODE_EXECUTION_ENDPOINT
              value: http://sandbox:8194
            - name: CODE_MAX_NUMBER
              value: "9223372036854775807"
            - name: CODE_MAX_NUMBER_ARRAY_LENGTH
              value: "1000"
            - name: CODE_MAX_OBJECT_ARRAY_LENGTH
              value: "30"
            - name: CODE_MAX_STRING_ARRAY_LENGTH
              value: "30"
            - name: CODE_MAX_STRING_LENGTH
              value: "80000"
            - name: CODE_MIN_NUMBER
              value: "-9223372036854775808"
            - name: CONSOLE_API_URL
            - name: CONSOLE_CORS_ALLOW_ORIGINS
              value: '*'
            - name: CONSOLE_WEB_URL
            - name: DB_DATABASE
              value: dify
            - name: DB_HOST
              value: db
            - name: DB_PASSWORD
              value: difyai123456
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: FILES_URL
            - name: INIT_PASSWORD
            - name: LOG_LEVEL
              value: INFO
            - name: MAIL_DEFAULT_SEND_FROM
              value: 'YOUR EMAIL FROM (eg: no-reply <no-reply@dify.ai>)'
            - name: MAIL_TYPE
            - name: MIGRATION_ENABLED
              value: "true"
            - name: MILVUS_HOST
              value: 127.0.0.1
            - name: MILVUS_PASSWORD
              value: Milvus
            - name: MILVUS_PORT
              value: "19530"
            - name: MILVUS_SECURE
              value: "false"
            - name: MILVUS_USER
              value: root
            - name: MODE
              value: api
            - name: QDRANT_API_KEY
              value: difyai123456
            - name: QDRANT_CLIENT_TIMEOUT
              value: "20"
            - name: QDRANT_URL
              value: http://qdrant:6333
            - name: REDIS_DB
              value: "0"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PASSWORD
              value: difyai123456
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_USERNAME
            - name: REDIS_USE_SSL
              value: "false"
            - name: RESEND_API_KEY
            - name: RESEND_API_URL
              value: https://api.resend.com
            - name: S3_ACCESS_KEY
              value: ak-difyai
            - name: S3_BUCKET_NAME
              value: difyai
            - name: S3_ENDPOINT
              value: https://xxx.r2.cloudflarestorage.com
            - name: S3_REGION
              value: us-east-1
            - name: S3_SECRET_KEY
              value: sk-difyai
            - name: SECRET_KEY
              value: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
            - name: SENTRY_DSN
            - name: SENTRY_PROFILES_SAMPLE_RATE
              value: "1"
            - name: SENTRY_TRACES_SAMPLE_RATE
              value: "1"
            - name: SERVICE_API_URL
            - name: SMTP_PASSWORD
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_SERVER
            - name: SMTP_USERNAME
            - name: SMTP_USE_TLS
              value: "true"
            - name: STORAGE_LOCAL_PATH
              value: storage
            - name: STORAGE_TYPE
              value: s3
            - name: TEMPLATE_TRANSFORM_MAX_LENGTH
              value: "80000"
            - name: VECTOR_STORE
              value: weaviate
            - name: WEAVIATE_API_KEY
              value: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
            - name: WEAVIATE_ENDPOINT
              value: http://weaviate:8080
            - name: WEB_API_CORS_ALLOW_ORIGINS
              value: '*'
          image: langgenius/dify-api:0.6.4
          name: api
          ports:
            - containerPort: 5001
              hostPort: 5001
              protocol: TCP
          volumeMounts:
            - mountPath: /app/api/storage
              name: api-claim0
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
