
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /mnt/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.template.overwrite: true

setup.kibana:
  host: "kibana:5601"

output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["kafka1:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000